### model
model_name_or_path: /data/wuyong/model/Qwen/Qwen2.5-Math-1.5B
quantization_bit: 4
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: all

### dataset
dataset: limo
cutoff_len: 16384
# cutoff_len: 8000
overwrite_cache: true
preprocessing_num_workers: 32
template: qwen

### output
output_dir: saves/Qwen2.5-1.5B-Instruct-limo/lora/sft
logging_steps: 1
save_strategy: epoch
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 1
learning_rate: 5.0e-6
num_train_epochs: 10
lr_scheduler_type: cosine
warmup_ratio: 0.0
bf16: true
ddp_timeout: 180000000
